# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: agautham's space
description: >- # this means to ignore newlines until "baseurl:"
  Hello, Friend! This is the place where I document my readings, my research, my ramblings on random subjects. These days, I am into the business side of things, particularly Product Management and Consulting/Strategy and a bit of others. So if you are into it, you might find something interesting here.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.agautham.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb

# Build settings
markdown: kramdown
theme: minima
plugins:
  # - jekyll-feed


header_pages: 
  - awesome_resources.md
  - about_me.md

defaults: 
    values: 
    author: "Adwaith Gautham"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus: 
  shortname: "www-pwnthebox-net-2"
